name: Unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8]
        django-version: [2.0, 2.1, 2.2, 3.0]

#    steps:
#      - name: Set up Python ${{ matrix.python-version }}
#      - uses: actions/checkout@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install Dependencies
#        run: |
#          pip install tox
#      - name: Run tox
#        run: |
#          tox

