name: Unit tests

on:


jobs:
  build:
    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8]
        django-version: [2.0, 2.1, 2.2, 3.0]

        include:
          - python-version: 2.7
            django-version: Django==1.11

    steps:
      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install tox
      - name: Run tox
        run: |
          tox

