name: Unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  build:
    name: Python ${{ matrix.python-version }}, django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
        django-version: [1.11, 2.2, 3.0, 3.1, 3.2]

        exclude:
          - python-version: 2.7
            django-version: 2.2

          - python-version: 2.7
            django-version: 3.0

          - python-version: 2.7
            django-version: 3.1

          - python-version: 2.7
            django-version: 3.2

          - python-version: 3.4
            django-version: 2.2

          - python-version: 3.4
            django-version: 3.0

          - python-version: 3.4
            django-version: 3.1

          - python-version: 3.4
            django-version: 3.2

          - python-version: 3.5
            django-version: 3.0

          - python-version: 3.5
            django-version: 3.1

          - python-version: 3.5
            django-version: 3.2

          - python-version: 3.6
            django-version: 1.11

          - python-version: 3.6
            django-version: 2.0

          - python-version: 3.7
            django-version: 1.11

          - python-version: 3.7
            django-version: 2.0

          - python-version: 3.8
            django-version: 1.11

          - python-version: 3.8
            django-version: 2.0

          - python-version: 3.8
            django-version: 2.1

          - python-version: 3.8
            django-version: 2.2

          - python-version: 3.9
            django-version: 1.11

          - python-version: 3.9
            django-version: 2.0

          - python-version: 3.9
            django-version: 2.1

          - python-version: 3.9
            django-version: 2.2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-gh-actions

      - name: Tox tests
        run: |
          tox -v
        env:
          DJANGO: ${{ matrix.django-version }}

#          pip install -e .
#          pip install "django~=${{ matrix.django-version }}.0"

#      - name: Run Test
#        run: |
#          python runtests.py
