name: Unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Python ${{ matrix.python-version }}, django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
        django-version: [111, 22, 30, 31, 32]

        exclude:
          - python-version: 2.7
            django-version: 22

          - python-version: 2.7
            django-version: 30

          - python-version: 2.7
            django-version: 31

          - python-version: 2.7
            django-version: 32

          - python-version: 3.4
            django-version: 22

          - python-version: 3.4
            django-version: 30

          - python-version: 3.4
            django-version: 31

          - python-version: 3.4
            django-version: 32

          - python-version: 3.5
            django-version: 30

          - python-version: 3.5
            django-version: 31

          - python-version: 3.5
            django-version: 32

          - python-version: 3.6
            django-version: 111

          - python-version: 3.6
            django-version: 20

          - python-version: 3.7
            django-version: 111

          - python-version: 3.7
            django-version: 20

          - python-version: 3.8
            django-version: 111

          - python-version: 3.8
            django-version: 20

          - python-version: 3.8
            django-version: 21

          - python-version: 3.8
            django-version: 22

          - python-version: 3.9
            django-version: 111

          - python-version: 3.9
            django-version: 20

          - python-version: 3.9
            django-version: 21

          - python-version: 3.9
            django-version: 22

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install tox
        run: pip install tox
      - name: Run Tests
        env:
          TOXENV: django${{ matrix.django-version }}
        run: tox

#          pip install -e .
#          pip install "django~=${{ matrix.django-version }}.0"

#      - name: Run Test
#        run: |
#          python runtests.py
